import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { ChevronLeft, ChevronDown } from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';
const FAQS = [
{
  q: 'How does Aavis analyze food?',
  a: 'Aavis securely utilizes advanced AI models to read ingredient labels and cross-references them against additive safety data. It then calculates a personalized health score based on your unique dietary profile.'
},
{
  q: 'Is my data private?',
  a: 'Yes. Your personal health profile and scan history are securely stored in our cloud database so you can access them across your devices. We use strict row-level security policies to ensure only you can view your data, and we never sell your information.'
},
{
  q: 'How accurate are the health scores?',
  a: 'Scores are generated by AI based on widely accepted nutritional guidelines, additive safety data, and your personal profile. They are for informational purposes and should not replace professional medical advice.'
},
{
  q: 'Can I edit my profile?',
  a: 'Yes. Go to the Profile tab to update your diet, allergens, or health conditions at any time. Your analysis results will immediately adapt to your new settings.'
},
{
  q: 'How do I manage my account?',
  a: 'You can sign out or manage your preferences from the Settings tab. Because your data is securely synced to the cloud, your scan history will be right where you left it when you log back in.'
},
{
  q: 'Why did a product show as "Hazardous" for me?',
  a: 'Hazardous verdicts can be triggered by harmful additives, direct allergen matches with your profile, or severe nutritional concerns relative to your specific health conditions.'
}];

export function Help() {
  const navigate = useNavigate();
  const [openIdx, setOpenIdx] = useState<number | null>(0);
  return (
    <div className="flex flex-col h-full bg-navy-900">
      <header className="pt-safe pt-6 px-4 pb-4 flex items-center border-b border-navy-800">
        <button
          onClick={() => navigate(-1)}
          className="p-2 -ml-2 text-content-secondary hover:text-white">
          
          <ChevronLeft className="w-6 h-6" />
        </button>
        <h1 className="font-display font-bold text-lg ml-2">Help & FAQ</h1>
      </header>

      <div className="flex-1 overflow-y-auto no-scrollbar p-6 space-y-3">
        {FAQS.map((faq, idx) => {
          const isOpen = openIdx === idx;
          return (
            <div
              key={idx}
              className="bg-navy-800 border border-navy-700 rounded-2xl overflow-hidden">
              
              <button
                onClick={() => setOpenIdx(isOpen ? null : idx)}
                className="w-full flex items-center justify-between p-4 text-left hover:bg-navy-700/50">
                
                <span className="font-medium pr-4">{faq.q}</span>
                <ChevronDown
                  className={`w-5 h-5 text-content-secondary flex-shrink-0 transition-transform ${isOpen ? 'rotate-180' : ''}`} />
                
              </button>
              <AnimatePresence>
                {isOpen &&
                <motion.div
                  initial={{
                    height: 0
                  }}
                  animate={{
                    height: 'auto'
                  }}
                  exit={{
                    height: 0
                  }}
                  transition={{
                    duration: 0.2
                  }}
                  className="overflow-hidden">
                  
                    <p className="px-4 pb-4 text-sm text-content-secondary leading-relaxed">
                      {faq.a}
                    </p>
                  </motion.div>
                }
              </AnimatePresence>
            </div>);

        })}
      </div>
    </div>);

}