import React, { useState } from 'react';
import { View, Text, StyleSheet, TouchableOpacity, ScrollView } from 'react-native';
import { ArrowLeft, ChevronDown, ChevronUp } from 'lucide-react-native';
import { getThemeColors } from '../lib/theme';
import { useAppContext } from '../context/AppContext';

const FAQS = [
  {
    q: 'How does Aavis analyze food?',
    a: 'Aavis securely utilizes advanced AI models to read ingredient labels and cross-references them against additive safety data. It then calculates a personalized health score based on your unique dietary profile.'
  },
  {
    q: 'Is my data private?',
    a: 'Yes. Your personal health profile and scan history are securely stored in our cloud database so you can access them across your devices. We use strict row-level security policies to ensure only you can view your data, and we never sell your information.'
  },
  {
    q: 'How accurate are the health scores?',
    a: 'Scores are generated by AI based on widely accepted nutritional guidelines, additive safety data, and your personal profile. They are for informational purposes and should not replace professional medical advice.'
  },
  {
    q: 'Can I edit my profile?',
    a: 'Yes. Go to the Profile tab to update your diet, allergens, or health conditions at any time. Your analysis results will immediately adapt to your new settings.'
  },
  {
    q: 'How do I manage my account?',
    a: 'You can sign out or manage your preferences from the Settings tab. Because your data is securely synced to the cloud, your scan history will be right where you left it when you log back in.'
  },
  {
    q: 'Why did a product show as "Hazardous" for me?',
    a: 'Hazardous verdicts can be triggered by harmful additives, direct allergen matches with your profile, or severe nutritional concerns relative to your specific health conditions.'
  }
];

export default function HelpScreen({ navigation }: any) {
  const { theme } = useAppContext();
  const colors = getThemeColors(theme);
  const styles = getStyles(colors);
  const [openIdx, setOpenIdx] = useState<number | null>(0);

  return (
    <ScrollView style={styles.scrollView} contentContainerStyle={styles.container} showsVerticalScrollIndicator={false}>
      {theme === 'dark' && <View style={styles.glowTop} />}

      <View style={styles.header}>
        <TouchableOpacity style={styles.backButton} onPress={() => navigation.goBack()}>
          <ArrowLeft color={colors.textPrimary} size={20} />
        </TouchableOpacity>
        <Text style={styles.headerTitle}>Help & FAQ</Text>
      </View>

      <View style={styles.list}>
        {FAQS.map((faq, idx) => {
          const isOpen = openIdx === idx;
          return (
            <View key={idx} style={styles.faqCard}>
              <TouchableOpacity 
                style={styles.faqHeader} 
                onPress={() => setOpenIdx(isOpen ? null : idx)}
              >
                <Text style={styles.faqQuestion}>{faq.q}</Text>
                {isOpen ? <ChevronUp color={colors.textSecondary} size={18} /> : <ChevronDown color={colors.textSecondary} size={18} />}
              </TouchableOpacity>
              {isOpen && (
                <View style={styles.faqAnswerContainer}>
                  <Text style={styles.faqAnswer}>{faq.a}</Text>
                </View>
              )}
            </View>
          );
        })}
      </View>
    </ScrollView>
  );
}

const getStyles = (colors: any) => StyleSheet.create({
  scrollView: {
    flex: 1,
    backgroundColor: colors.background,
  },
  container: {
    paddingHorizontal: 24,
    paddingTop: 60,
    paddingBottom: 40,
  },
  glowTop: {
    position: 'absolute',
    top: -50,
    right: -50,
    width: 280,
    height: 280,
    backgroundColor: '#10b981',
    borderRadius: 140,
    opacity: 0.04,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 24,
  },
  backButton: {
    padding: 10,
    backgroundColor: colors.isDark ? 'rgba(255, 255, 255, 0.03)' : 'rgba(0, 0, 0, 0.02)',
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 12,
    marginRight: 16,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: colors.textPrimary,
  },
  list: {
    gap: 12,
    marginTop: 8,
  },
  faqCard: {
    backgroundColor: colors.card,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 20,
    overflow: 'hidden',
  },
  faqHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 16,
  },
  faqQuestion: {
    fontSize: 14,
    fontWeight: 'bold',
    color: colors.textPrimary,
    flex: 1,
    marginRight: 16,
  },
  faqAnswerContainer: {
    paddingHorizontal: 16,
    paddingBottom: 16,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    paddingTop: 12,
  },
  faqAnswer: {
    fontSize: 13,
    lineHeight: 18,
    color: colors.textSecondary,
  },
});
